version: '3.8'

services:
  etkinlikweb:
    image: etkinlikweb
    build:
      context: ./EtkinlikWeb
    ports:
      - "5173:5173"
    networks:
      - etkinlik_network

  sampas_mobil_etkinlik:
    image: sampas_mobil_etkinlik
    build:
      context: ./Sampas_Mobil_Etkinlik
    ports:
      - "5262:5262"
    networks:
      - etkinlik_network

networks:
  etkinlik_network:
    driver: bridge
